Fix/nex 1641/allows to skip base64 assets
oat-sa/extension-tao-item pull request #424
Opened 2020-09-01 05:27 UTC by boajer

2020-09-01 10:21 UTC, siwane reviewed
Is it possbile to have unit test?
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-09-02 08:23 UTC, siwane approved these changes

2020-09-03 14:59 UTC, mike-ionut-mihai-sandu-tao approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-09-03 15:02 UTC, mike-ionut-mihai-sandu-tao requested changes
let's please update the unit test

2020-09-03 15:17 UTC, merged