Task/aut 968/import item
oat-sa/extension-tao-item pull request #527
Opened 2021-09-17 08:00 UTC by AnastasiaArcadia

**Related to:** https://oat-sa.atlassian.net/browse/AUT-968

Added import items tests

**How to test:**
- Run items test

2021-09-20 07:31 UTC, Silvia-loza reviewed
All looks good, however I can't get two of the tests to pass in my local.
![image](https://user-images.githubusercontent.com/60346520/133968838-126d1274-e7cf-475c-af92-b1789cd51023.png)

2021-09-20 07:39 UTC, bziondik requested changes

2021-09-20 07:39 UTC, bziondik commented on views/cypress/tests/item.spec.js
> +    describe('Import', () => {
I think better to move import and then export in separate `spec.js` file. Because it take more time and previous tests when fail can impact this test

2021-09-20 07:45 UTC, bziondik requested changes
Both failed for me 
![image](https://user-images.githubusercontent.com/25976342/133970387-2d1e5227-d0c7-40f2-b261-0da4ef94dbf3.png)

2021-09-20 13:01 UTC, Silvia-loza approved these changes
All looks good and tests pass consistently, Great job! 
- [ ] New code is covered by tests (if applicable)
- [X] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [X] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

2021-09-22 16:01 UTC, bziondik requested changes
Still have error
![image](https://user-images.githubusercontent.com/25976342/134379564-34c83043-2843-40e0-b978-6516112e18d1.png)
Issue that Label in form is updated in command `renameSelectedClass`
but request is still ongoing and tree is not updated and contain old class name, thats why command `selectNode` fails

2021-09-23 14:11 UTC, merged