fix: set item resource type in form options
oat-sa/extension-tao-item pull request #602
Opened 2022-11-23 18:51 UTC by bartlomiejmarszal

Related to https://github.com/oat-sa/extension-tao-resource-workflow/pull/42

Define Item resourceType in form options

How to reproduce:

- Ensure your instance has taoResourceWorkflow installed
- Create item with content
- Export Item
- Open another environment with taoResourceWorkflow installed
- Import item
- Ensure the item has initially stated and defined in the workflow

2022-11-24 14:31 UTC, andreluizmachado approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2022-11-24 14:32 UTC, andreluizmachado requested changes
please fix unit tests

2022-11-24 16:13 UTC, andreluizmachado approved these changes

2022-11-25 08:22 UTC, pnal approved these changes
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on playground (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2022-11-25 13:34 UTC, merged